Repository thelastpickle/cassandra-medusa, pull requests merged in 2020-06, with the labels that each got.

#143 Fix debian packaging which broke due to gevent not building anymore.
  packaging/docker-build/Dockerfile
Labels: bug

#139 Move digest computation to storage implementations. Fixes #123
  medusa/backup.py
  medusa/storage/abstract_storage.py
  medusa/storage/google_storage.py
  medusa/storage/local_storage.py
  medusa/storage/s3_rgw.py
  medusa/storage/s3_storage.py
  medusa/verify.py
  tests/backup_test.py
  tests/storage_test.py
Labels: bug, enhancement

#138 Add wait for node shutdown. Fix healtcheck config. Fixes #72
  medusa/cassandra_utils.py
  medusa/config.py
  medusa/restore_node.py
  medusa/verify_restore.py
  tests/cassandra_utils_test.py
  tests/integration/features/steps/integration_steps.py
  tests/purge_test.py
  tests/restore_cluster_test.py
  tests/restore_node_test.py
  tests/storage_test.py
  tests/storage_test_with_prefix.py
Labels: LHF, bug, critical
